<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-CTHIPDashboard-f6349b05-29ce-424d-9579-5361068f6c52</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Chart.js" Version="3.7.1" />
    <PackageReference Include="EPPlus" Version="8.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11" />
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="4.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.11" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="Select2.js" Version="4.0.13" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include=".github\workflows\" />
    <Folder Include="Templates\" />
    <Folder Include="wwwroot\images\" />
    <Folder Include="wwwroot\uploads\enrollees\" />
  </ItemGroup>

</Project>
