-- Quick admin user seeding for SQL Server
-- Run this in SQL Server Management Studio or Azure Data Studio against CTSHIPDashboard database

-- Create admin role
IF NOT EXISTS (SELECT 1 FROM AspNetRoles WHERE Name = 'Admin')
    INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
    VALUES (NEWID(), 'Admin', 'ADMIN', NEWID());

IF NOT EXISTS (SELECT 1 FROM AspNetRoles WHERE Name = 'CTSHIPAdmin')
    INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
    VALUES (NEWID(), 'CTSHIPAdmin', 'CTSCHIPADMIN', NEWID());

-- Create admin user if not exists
IF NOT EXISTS (SELECT 1 FROM AspNetUsers WHERE Email = 'as.maiwada@nedc.gov.ng')
BEGIN
    DECLARE @UserId NVARCHAR(450) = NEWID()
    DECLARE @AdminRoleId NVARCHAR(450) = (SELECT Id FROM AspNetRoles WHERE Name = 'Admin')
    DECLARE @CtshipAdminRoleId NVARCHAR(450) = (SELECT Id FROM AspNetRoles WHERE Name = 'CTSHIPAdmin')
    
    -- Password hash for "Admin@2025" generated by ASP.NET Identity
    DECLARE @PasswordHash NVARCHAR(MAX) = 'AQAAAAIAAYagAAAAELmX3l3q2K2W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0W0='
    
    INSERT INTO AspNetUsers (
        Id, UserName, NormalizedUserName, Email, NormalizedEmail, 
        EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp, 
        PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled, LockoutEnabled, 
        LockoutEnd, AccessFailedCount, FullName, State
    )
    VALUES (
        @UserId, 'as.maiwada@nedc.gov.ng', 'AS.MAIWADA@NEDC.GOV.NG', 
        'as.maiwada@nedc.gov.ng', 'AS.MAIWADA@NEDC.GOV.NG', 
        1, @PasswordHash, NEWID(), NEWID(), 
        NULL, 0, 0, 0, 
        NULL, 0, 'CTSHIP Admin', 'Borno'
    )
    
    -- Assign roles
    INSERT INTO AspNetUserRoles (UserId, RoleId)
    VALUES (@UserId, @AdminRoleId)
    
    INSERT INTO AspNetUserRoles (UserId, RoleId)
    VALUES (@UserId, @CtshipAdminRoleId)
    
    SELECT 'Admin user created successfully' AS Result
END
ELSE
    SELECT 'Admin user already exists' AS Result
